project:
  type: website

lang: es

website:
  page-navigation: true
  title: "Diabb Zegpi"
  site-url: https://zegpi.com
  favicon: dyl-dark.ico
  google-analytics: "G-63PKLV6G58"
  description: "Blog personal de Diabb Zegpi, donde leerás sobre aplicaciones de ciencia de datos."
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Diabb Zegpi. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: whatsapp
        href: https://wa.me/56978020601
        target: _blank
      - icon: github
        href: https://github.com/DiabbZegpi
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/diabbzegpi
        target: _blank
      - icon: envelope
        href: diabbluis@gmail.com
        target: _blank
      - icon: twitter
        href: https://x.com/Diabb6
        target: _blank
  navbar:
    logo: dyl-light.svg
    right:
      - text: About
        menu:
          - text: Español
            href: about-es.qmd
          - text: English
            href: about-en.qmd
      - text: Datos y Leyendas
        href: index.qmd
      - text: Elo MyL (Alpha)
        href: elo-myl.qmd
      - icon: rss
        href: _site/index.xml

  comments:
    giscus:
      repo: DiabbZegpi/mercaderes
      language: es


format:
  html:
    smooth-scroll: true
    theme:
      - Sandstone
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    linkcolor: "#E64833"
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

execute:
  freeze: auto

resources:
  - "fonts/*"