project:
  type: website

website:
  title: "Diabb Zegpi"
  site-url: https://zegpi.com/
  description: "Blog personal de Diabb Zegpi, donde leerás sobre aplicaciones de ciencia de datos."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/DiabbZegpi
      - icon: twitter
        href: https://x.com/Diabb6

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

comments:
  giscus:
    repo: DiabbZegpi/mercaderes